<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TemplateItem;


class TemplateItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [

            [
                'template_section_id' => 1,
                'item_code' => '1.01',
                'description' => "Allowance for design fees associated with the creation of project drawing packs, including general arrangements and RCP's.",
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 6500,
                'mark_up' => 20,
            ],

             [
                'template_section_id' => 2,
                'item_code' => '2.01',
                'description' => 'Full Time Site Manager',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 1625,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.02',
                'description' => 'Working Site Supervisor',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.03',
                'description' => 'Saturday Out of hours working & deliveries (noise restrictions)',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.04',
                'description' => 'Sunday Out of hours working & deliveries (noise restrictions)',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.05',
                'description' => 'Attendant labour',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 750,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.06',
                'description' => 'Clear away all site waste as it accumulates during the course of the works',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 540,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.07',
                'description' => 'Supply & Install for delivery of site set up equipment, plant & H & S items also collection on completion of works',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.08',
                'description' => 'Provide small plant and access staging\'s',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 310,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.09',
                'description' => 'Provide temporary site offices and meeting facilities',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 950,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.10',
                'description' => 'Mobile communications',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.11',
                'description' => 'Site expenses, welfare items, consumables, I.T and printer, etc.',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 150,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.12',
                'description' => 'Protection to demise and common areas',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 2100,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.13',
                'description' => 'Site Guest PPE Equipment as required for H&S (Provision for 2no)',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 450,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.14',
                'description' => 'Toilet facilities for site staff & sub contractors',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 250,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.15',
                'description' => 'Site personal welfare facilities',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 250,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.16',
                'description' => 'Fuels, electricity, gas etc. by Client',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.17',
                'description' => 'Temporary 110 volt / RCB protected power for the works',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 850,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.18',
                'description' => '4 way power splitter box',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.19',
                'description' => 'Welfare / Charger sockets',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.20',
                'description' => 'Temporary lighting for the works',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 650,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.21',
                'description' => 'Temporary emergency 5ft lighting to stair core',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.22',
                'description' => 'Temporary water for the works',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.23',
                'description' => 'Security site tool box',
                'quantity' => 1,
                'unit' => 'weeks',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.24',
                'description' => 'Temporary screens & hoardings',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 600,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.25',
                'description' => 'Plastic pedestrian barriers 2.000 to open floor areas',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.26',
                'description' => 'Transfer prevention dust matts and equipment',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.27',
                'description' => 'Compliance with Health & Safety (CDM) regulations',
                'quantity' => 1,
                'unit' => 'no',
                'rate' => 275,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.28',
                'description' => 'Fire prevention equipment & signage',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.29',
                'description' => 'Final Builders Detailed Clean on completion of the works',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 1500,
                'mark_up' => 35,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.30',
                'description' => 'Site survey',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 0,
                'mark_up' => 0,
            ],
            [
                'template_section_id' => 2,
                'item_code' => '2.31',
                'description' => 'Remove all glass to a recycle depot via van',
                'quantity' => 1,
                'unit' => 'item',
                'rate' => 0,
                'mark_up' => 35,
            ],

             [
        'template_section_id' => 3,
        'item_code' => '3.01',
        'description' => 'Building Control Fees',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 2100,
        'mark_up' => 20,
    ],
    [
        'template_section_id' => 3,
        'item_code' => '3.02',
        'description' => 'Landlord Approval and Preconstruction Fees',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 1500,
        'mark_up' => 20,
    ],
    [
        'template_section_id' => 3,
        'item_code' => '3.03',
        'description' => 'Demolition & Refurbishment Survey - Taking of samples in accordance HSG264 and deposited with an independent UKAS accredited laboratory for analysis in accordance with HSG248. Analysis will be certified in the final report.',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 650,
        'mark_up' => 20,
    ],
    [
        'template_section_id' => 3,
        'item_code' => '3.04',
        'description' => 'Works Insurance - Joint Names Cover - By Client',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 20,
    ],

     [
        'template_section_id' => 4,
        'item_code' => '4.01',
        'description' => "In line with the requirements of the Construction (Design & Management) Regulations 2020, a Principal Designer must be formally appointed by the client to co-ordinate the design aspects of the project. This role is in addition to the responsibilities of the Principal Contractor, which we have allowed for, however Imperial can act as the role as Principal Designer if requested by the client.

Initial site assessment – identifying significant / unusual risks and constraints associated with the site.
Planning, managing and monitoring the pre-construction phase – co-ordinating matters relating to health and safety.
Ensuring that designers comply with their duties in Regulation 9 of CDM 2015.
Developing and maintaining a CDM risk register – capturing residual risk information.
Notification of the HSE – F10 (where applicable).
Attendance at the pre-start meeting or a progress meeting.
Supporting the Principal Contractor with the Construction Phase Plan – including review.
Development of the CDM Health and Safety File.",
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 3750,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.02',
        'description' => "As Principal Contractor, Imperials role in-line with the Regulations including responsibility for:-",
        'quantity' => 1,
        'unit' => 'note',
        'rate' => 0,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.03',
        'description' => "Providing advice to the Client on his responsibilities under the Regulations.",
        'quantity' => 1,
        'unit' => 'note',
        'rate' => 0,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.04',
        'description' => "Notification and subsequent updates of project details to the H.S.E.",
        'quantity' => 1,
        'unit' => 'note',
        'rate' => 0,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.05',
        'description' => "Establishing risk assessments for unavoidable hazards anticipated during construction.",
        'quantity' => 1,
        'unit' => 'note',
        'rate' => 0,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.06',
        'description' => "Securing existing documentation relevant to Health & Safety of the project (including as-built drawings, O&M Manuals, Health & Safety file, Asbestos Register, etc.).",
        'quantity' => 1,
        'unit' => 'note',
        'rate' => 0,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.07',
        'description' => "Developing the initial Construction Phase and Health & Safety Plans.",
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 550,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.08',
        'description' => "Provision / collating O&M manuals",
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 900,
        'mark_up' => 35,
    ],
    [
        'template_section_id' => 4,
        'item_code' => '4.09',
        'description' => "Allow for a 1zone water leak detection system to include control panel with visual & audible alarm. Detectors to be placed with comms room drip tray",
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 1320,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 5,
        'item_code' => '5.01',
        'description' => 'Solid Partition Strip Out - Dismantle and disposal of existing plasterboard partitions',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.02',
        'description' => 'Glazed Partition Strip Out - Dismantle and disposal of existing glazed partitions',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.03',
        'description' => 'Door Set Strip Out - Dismantle and disposal of existing door sets',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.04',
        'description' => 'Carpet Tile Strip Out - Lift up and disposal of carpet tiles',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.05',
        'description' => 'Vinyl Flooring Strip Out - Lift up and disposal of vinyl flooring',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.06',
        'description' => 'Grid Ceiling Strip Out - Dismantle and disposal of metal ceiling tiles, grid and hangers',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],
    [
        'template_section_id' => 5,
        'item_code' => '5.07',
        'description' => 'Raised Access Floor Strip Out - Allow to carefully lift the raised access floor tiles and associated pedestals',
        'quantity' => 1,
        'unit' => 'item',
        'rate' => 0,
        'mark_up' => 25,
    ],

     [
        'template_section_id' => 6,
        'item_code' => '6.01',
        'description' => 'Floor Box Cut Outs - Create cut outs to raised access floor tiles for new floor boxes',
        'quantity' => 1,
        'unit' => 'no',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 6,
        'item_code' => '6.02',
        'description' => 'Uplift & Relay Raised Access Floor - Uplift and relay 40% of existing RAF to facilitate electrical/data installation',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 6,
        'item_code' => '6.03',
        'description' => 'New Raised Access Floor - Supply and install 600 x 600 mm x 29 mm thick, medium duty raised access chipboard floor tile with a galvanised steel face (Working load 4.60 kN)',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 6,
        'item_code' => '6.04',
        'description' => 'Fire Barrier - Install under floor fire barrier',
        'quantity' => 1,
        'unit' => 'LM',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 6,
        'item_code' => '6.05',
        'description' => 'Cut & Support Raised Floor either side of Slab to Slab Partitions',
        'quantity' => 1,
        'unit' => 'LM',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 6,
        'item_code' => '6.06',
        'description' => 'Lower Raised Floor for Floor Finishes',
        'quantity' => 1,
        'unit' => 'LM',
        'rate' => 12,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.01',
        'description' => 'Specialist Preliminaries - Allow for specialist subcontractors Site Management, Preliminaries and plant / access equipment',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Plasterboard Partitions ---
    [
        'template_section_id' => 7,
        'item_code' => '7.02',
        'description' => '100mm Solid Partition Walls - FFL to FCL - Supply and install new 100mm partitioning made up of 50mm trackwork with 2 x 12.5mm plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.03',
        'description' => '100mm Solid Partition Walls - Slab to Slab - Supply and install new 100mm partitioning made up of 50mm trackwork with 2 x 12.5mm plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.04',
        'description' => '100mm Solid Partition Walls - FFL to FCL - 60 Minute Fire Rated - Supply and install new 100mm partitioning made up of 50mm trackwork with 2 x 12.5mm Fire Rated plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.05',
        'description' => '100mm Solid Partition Walls - Slab to Slab - 60 Minute Fire Rated - Supply and install new 100mm partitioning made up of 50mm trackwork with 2 x 12.5mm Fire Rated plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.06',
        'description' => '120mm Solid Partition Walls - FFL to FCL - Supply and install new 120mm partitioning made up of 70mm trackwork with 2 x 12.5mm plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.07',
        'description' => '120mm Solid Partition Walls - Slab to Slab - Supply and install new 120mm partitioning made up of 70mm trackwork with 2 x 12.5mm plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.08',
        'description' => '120mm Solid Partition Walls - FFL-FCL - 60 Minute Fire Rated - Supply and install new 120mm partitioning made up of 70mm trackwork with 2 x 12.5mm Fire Rated plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.09',
        'description' => '120mm Solid Partition Walls - Slab to Slab - 60 Minute Fire Rated - Supply and install new 120mm partitioning made up of 70mm trackwork with 2 x 12.5mm Fire Rated plasterboards either side. Taped & jointed. RAF to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Bulkheads ---
    [
        'template_section_id' => 7,
        'item_code' => '7.10',
        'description' => '100mm Solid Bulkheads - Supply and install new 100mm bulkhead above doors and glazing made up of 50mm trackwork and 2 x 12.5mm plasterboards. T&J',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.11',
        'description' => '100mm Solid Bulkheads - 60 Minute Fire Rated - Supply and install new 100mm bulkhead above doors and glazing made up of 50mm trackwork and 2 x 12.5mm plasterboards. T&J',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 135,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.12',
        'description' => '120mm Solid Bulkheads - Supply and install new 120mm bulkhead above doors and glazing made up of 70mm trackwork and 2 x 12.5mm plasterboards. T&J',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.13',
        'description' => '120mm Solid Bulkheads - 60 Minute Fire Rated - Supply and install new 120mm bulkhead above doors and glazing made up of 70mm trackwork and 2 x 12.5mm plasterboards. T&J',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 135,
        'mark_up' => 30,
    ],

    // --- Glazed Partitions ---
    [
        'template_section_id' => 7,
        'item_code' => '7.14',
        'description' => 'Single Glazed Toughened Partitions - Supply and install new 12.8mm Single Glazed Toughened full height frameless glass partitioning fitted within 25 x 25mm powder coated aluminium perimeter track',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.15',
        'description' => 'Single Glazed Acoustic Partitions - Supply and install new 12.8mm Single Glazed Acoustic full height frameless glass partitioning fitted within 25 x 25mm powder coated aluminium perimeter track',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.16',
        'description' => 'Double Glazed Partitions - Supply and install new 2 x 12.8mm Double Glazed full height frameless glass to glass dry jointed double glazed partitioning fitted within 25 x 25mm powder coated aluminium perimeter track',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Skirting & Misc ---
    [
        'template_section_id' => 7,
        'item_code' => '7.17',
        'description' => 'Allowance for high level penetrations through partitions and bulkheads including letterbox details and making good',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.18',
        'description' => 'Ply Reinforcements - Supply & Install Ply reinforcement to partitioning as required for installation of TVs etc.',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.19',
        'description' => 'Abutments - Allow for recessed head detail, wall abutments, reducer posts, door frame inserts, fair ends and door openings associated with the solid and glass partitioning.',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.20',
        'description' => 'Penetration Sealant - Allowance to seal around penetrations to partitions, bulkheads and abutments to slab',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.21',
        'description' => 'Plant On Skirting - Supply and installation of new primed MDF skirting 100mm x 12mm to new drywall',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 7,
        'item_code' => '7.22',
        'description' => 'Recessed Skirting - Supply and installation of new primed MDF recessed skirting 100mm x 12mm to new drywall',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],

     [
        'template_section_id' => 8,
        'item_code' => '8.01',
        'description' => 'Folding Wall 01 (MFC) - Supply & Installation of NEW Top Hung folding wall with Single Point Suspension 130mm thick, suspended from the structural slab, finished in White MFC, laboratory tested to XX dB',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 8,
        'item_code' => '8.02',
        'description' => 'Folding Wall 02 (Fabric) - Supply & Installation of NEW Top Hung folding wall with Single Point Suspension 130mm thick, suspended from the structural slab, finished in XXXX fabric, laboratory tested to XX dB',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 8,
        'item_code' => '8.03',
        'description' => 'Allowance for Structural Engineering review to support the folding wall installation, inclusive of structural design and analysis report',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

     [
        'template_section_id' => 9,
        'item_code' => '9.01',
        'description' => 'Specialist Preliminaries - Allow for specialist subcontractors Site Management, Preliminaries and plant / access equipment',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Solid Timber Doors ---
    [
        'template_section_id' => 9,
        'item_code' => '9.02',
        'description' => 'Standard Height Paint Grade Single Doors - Supply and installation of 838 x 1981 x 44mm solid core paint grade timber doors with aluminium frames and satin stainless steel ironmongery',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.03',
        'description' => 'Standard Height Paint Grade Single Doors - FD60 - Supply and installation of 838 x 1981 x 44mm FD60 solid core paint grade timber doors with aluminium frames and satin stainless steel ironmongery',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.04',
        'description' => 'Full Height Paint Grade Single Doors - Supply and installation of full height 838 x 44mm solid core paint grade timber doors with aluminium frames and satin stainless steel ironmongery',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.05',
        'description' => 'Full Height Paint Grade Single Doors - FD60 - Supply and installation of full height 838 x 44mm FD60 solid core paint grade timber doors with aluminium frames and satin stainless steel ironmongery',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Laminate Doors ---
    [
        'template_section_id' => 9,
        'item_code' => '9.06',
        'description' => 'Supply & Install single laminated door, non fire rated, with 1500 x 150mm vision panels and door closer',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.07',
        'description' => 'Supply & Install leaf and a half laminated door, non fire rated, with 1500 x 150mm vision panels and door closer',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.08',
        'description' => 'Supply & Install double laminated door set, non fire rated, with 1500 x 150mm vision panels and door closer',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.09',
        'description' => 'Supply & Install single laminated lab door, fire rated, with 200 x 600mm vision panels and door closer',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Hardware & Misc ---
    [
        'template_section_id' => 9,
        'item_code' => '9.10',
        'description' => 'Overhead Door Closers - Supply and installation of mechanically operated overhead door closers to selected doors',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.11',
        'description' => 'Supply and install mortice dead lock complete with cylinder and turn',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.12',
        'description' => 'Vision Panels - Extra over for vision panels to above doors',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.13',
        'description' => 'Frame Seals - Supply and installation of frame seals (including leading edge seal for double doors)',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.14',
        'description' => 'Digilock - Supply & Install mechanical digilock to Comms/Server Room door',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.15',
        'description' => 'Overhead Door Closers - Supply and installation of mechanically operated overhead door closers to selected doors (duplicate entry included as separate line item)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    // --- Glazed Doors ---
    [
        'template_section_id' => 9,
        'item_code' => '9.16',
        'description' => 'Single Toughened Door - Supply & Install single toughened glazed 12.8mm door in frame system, including back-to-back Guardsman handles finished in RAL 9050 (Black)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.17',
        'description' => 'Double Toughened Door - Supply & Install double toughened glazed 2 x 12.8mm doors in frame system, including back-to-back Guardsman handles finished in RAL 9050 (Black)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.18',
        'description' => 'Single Acoustic Door - Supply & Install single acoustic glazed 12.8mm door in frame system, including back-to-back Guardsman handles finished in RAL 9050 (Black)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 9,
        'item_code' => '9.19',
        'description' => 'Double Acoustic Door - Supply & Install double glazed acoustic 2 x 12.8mm doors in frame system, including back-to-back Guardsman handles finished in RAL 9050 (Black)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

     [
        'template_section_id' => 10,
        'item_code' => '10.01',
        'description' => 'Ceiling Attendance - Allowance for general ceiling attendances to facilitate lighting and FCU relocations',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.02',
        'description' => 'Supply and install new MF ceilings made of metal studwork and 12.5mm plasterboards',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.03',
        'description' => 'Supply and install new MF margins made of metal studwork and 12.5mm plasterboards',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.04',
        'description' => 'Supply and install new 600x600mm Grid Ceiling made of Mineral Fibre ceiling tiles within a supporting grid system',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.05',
        'description' => 'Supply and install new 600x600mm Grid Ceiling made of Metal Perforated ceiling tiles within a supporting grid system',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.06',
        'description' => 'Supply and install plasterboard upstands made of metal studwork and 12.5mm plasterboards',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.07',
        'description' => 'Allowance to create recess trough detail for LEDs as per RCP',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.08',
        'description' => 'Supply and install access panels to MF ceiling for services access',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 10,
        'item_code' => '10.09',
        'description' => 'Allowance for fire barriers at increments determined by fire strategy and building control',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],

     [
        'template_section_id' => 11,
        'item_code' => '11.01',
        'description' => 'Sub Contractor Prelims - Inclusive of O&M Manuals, Testing and Certification',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.02',
        'description' => 'Electrical Isolations - Isolations to electrical connections prior to strip out',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.03',
        'description' => 'Mains',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.04',
        'description' => 'Retain existing distribution boards and update circuit charts',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.05',
        'description' => 'Allow to supply and install RCBOs to new circuitry',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.06',
        'description' => 'Allow to supply and install MCBs to new circuitry',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.07',
        'description' => 'Allow to supply and install 8 Way TPN distribution board complete with main switch - metered',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.08',
        'description' => 'Allow to supply and install submain cabling to new distribution boards',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.09',
        'description' => 'Allow to supply and install three phase MCB devices to suit the new installation - up to 32amp',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.10',
        'description' => 'Allow to supply and install three phase MCB devices to suit the new installation - up to 32amp (duplicate)',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.11',
        'description' => 'Small Power - Allow to supply and install 4 compartment floor box c/w 2 x DSSO and 1 x 4 gang data plate, spare for AV+ 5m tap off lead',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.12',
        'description' => 'To provide 13a dual earth sockets at high level in walls for TV screen to include wiring in accordance with section 543.7 BS 7671 2008',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 11,
        'item_code' => '11.13',
        'description' => 'Allow to supply and install 2 gang individually fused RCD/RCBO power bars c/w wieland end caps to lower section of desk',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 12,
        'item_code' => '12.01',
        'description' => 'Existing Lighting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.02',
        'description' => 'Allow to remove the existing light fittings to make way for the new lighting design throughout the floors',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.03',
        'description' => 'New Lighting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.04',
        'description' => 'FL1 - Allowance to supply & install NEW XXXX feature light as per RCP drawing',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.05',
        'description' => 'FL2 - Allowance to supply & install NEW XXXX feature light as per RCP drawing',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.06',
        'description' => 'Allow to supply and install suspended 2500mm LED linear light fitting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.07',
        'description' => 'Allow to supply and install suspended 2500mm LED linear light fitting c/w emergency battery pack',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.08',
        'description' => 'Allow to supply and install suspended 4200mm LED linear light fitting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.09',
        'description' => 'Allow to supply and install suspended 4500mm LED linear light fitting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.10',
        'description' => 'Allow to supply and install suspended 5000mm LED linear light fitting',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.11',
        'description' => 'Allow to supply and install surface mounted canister downlights c/w dali dimmable control gear',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.12',
        'description' => 'Allow to supply and install surface mounted canister downlights c/w dali dimmable control gear and EMPRO EMG battery back up',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.13',
        'description' => 'Allow to supply and install suspended canister downlights c/w dali dimmable control gear',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 12,
        'item_code' => '12.14',
        'description' => 'Allow to supply and install suspended canister downlights c/w dali dimmable control gear and EMPRO EMG battery back up',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],

        [
        'template_section_id' => 13,
        'item_code' => '13.01',
        'description' => 'Fire Alarm',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.02',
        'description' => 'Supply & Install for New / relocated smoke detectors and sounders as required',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.03',
        'description' => 'Allow to carry out modifications and enhancements to the existing fire alarm system to meet the requirements of the new layouts. Includes re-commissioning of system upon completion of works',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.04',
        'description' => 'Allowance to recommission the Fire Alarm system using the building incumbent XXXX',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.05',
        'description' => 'Allowance to install temporary fire alarm system to the floor for the duration of the construction phase',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.06',
        'description' => 'Sprinklers',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.07',
        'description' => 'Allowance to modify the existing Sprinkler pipework and Sprinkler head location to suit NEW layout and abide by regulations',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.08',
        'description' => 'Allowance to recommission the sprinkler system using the building incumbent XXXX',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.09',
        'description' => 'Fire Curtain',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 13,
        'item_code' => '13.10',
        'description' => 'Allowance to supply & install fire curtain to proposed location XXXX',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

      [
        'template_section_id' => 14,
        'item_code' => '14.01',
        'description' => 'High Level Cat6 Network - Supply & Install Cat6 network outlets at H/L for Wi-Fi',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.02',
        'description' => 'Cat6 Network Outlets - Supply & Install Cat6 network outlets grommets',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.03',
        'description' => 'High Level Cat6a Network - Supply & Install Cat6 network outlets at H/L for Wi-Fi',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.04',
        'description' => 'Cat6a Network Outlets - Supply & Install Cat6 network outlets grommets',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.05',
        'description' => 'HDMI Connections - Supply & Install HDMI connections',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.06',
        'description' => '18U Comms Rack - Supply & Install of Comms Rack - 18U',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.07',
        'description' => '42U Comms Rack - Supply & Install of Comms Rack - 42U',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 14,
        'item_code' => '14.08',
        'description' => 'GOP Boxes - Supply & Install GOP Boxes for Data presentation from Grommets',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    
     [
        'template_section_id' => 15,
        'item_code' => '15.01',
        'description' => 'Access Control',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 15,
        'item_code' => '15.02',
        'description' => 'Allowance to supply and Install new internal access control system compatible with landlords control system',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 15,
        'item_code' => '15.03',
        'description' => 'Allowance to supply XXNo of landlord access control cards to incoming tenant employees',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 15,
        'item_code' => '15.04',
        'description' => 'CCTV',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 45,
    ],
    [
        'template_section_id' => 15,
        'item_code' => '15.05',
        'description' => 'Allowance to supply and Install CCTV system compatible with landlords control system',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 16,
        'item_code' => '16.01',
        'description' => 'Note - Subject to confirmation of landlords intent to replace the VRV system in its entirety, meeting book W/C 1st August to discuss',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.02',
        'description' => 'Mechanical Isolations and Drain Down',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    // Preliminaries
    [
        'template_section_id' => 16,
        'item_code' => '16.03',
        'description' => 'Design calculations',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.04',
        'description' => 'Production of mechanical drawings',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.05',
        'description' => 'Allow for the validation of existing BMS system',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.06',
        'description' => 'Allow for the validation of Daikin VRV system',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.07',
        'description' => 'Allow for the hire of access equipment',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.08',
        'description' => 'Allow for the production of O&M manual & Building log book updates',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.09',
        'description' => 'Allow for chlorination of new domestic water pipework',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    // Comfort Cooling System
    [
        'template_section_id' => 16,
        'item_code' => '16.10',
        'description' => 'Allow for the recovery of refrigerant from VRV system',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.11',
        'description' => 'Allow for the removal of existing round flow cassette',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.12',
        'description' => 'Allow for the relocation of removed round flow cassette',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.13',
        'description' => 'Allow for the supply & installation of new round flow cassette',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.14',
        'description' => 'Allow for the supply & installation of new BC refrigerant control box',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.15',
        'description' => 'Allow for the supply & installation of new Madoka hard wired controller',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    // Comms Room Cooling
    [
        'template_section_id' => 16,
        'item_code' => '16.16',
        'description' => 'Allow for the supply & installation of new 5kw wall mounted indoor unit',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.17',
        'description' => 'Allow for the supply & installation of new 5kw outdoor condenser',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.18',
        'description' => 'Allow for the supply & installation of new containment, pipework, lagging & comms between indoor unit & outdoor',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    [
        'template_section_id' => 16,
        'item_code' => '16.19',
        'description' => 'Allow for the supply & installation of drip tray. To allow for leak detection',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],
    // Teapoint Extract
    [
        'template_section_id' => 16,
        'item_code' => '16.20',
        'description' => 'Allow for the supply & installation of new TD 150 extract fan, attenuator, extract grille & spiral ducting to discharge at existing central plant bell mouth',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 40,
    ],

     [
        'template_section_id' => 17,
        'item_code' => '17.01',
        'description' => 'Allow for the running in of new 15mm cold water feed from nearest LL supply',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.02',
        'description' => 'Allow for the supply & installation of new 15lt 3kw unvented water heater',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.03',
        'description' => 'Allow for the supply & installation of new waste water pump including pumped waste pipework to nearest SVP',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.04',
        'description' => 'Allow for 1st & 2nd fix pipework',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.05',
        'description' => 'Allow for lagging of new pipework',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    // Zip Tap
    [
        'template_section_id' => 17,
        'item_code' => '17.06',
        'description' => 'Instant Boiling Water Tap Supply - Allowance to provide domestic water supply to Instant Boiling Water Tap',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.07',
        'description' => 'Supply and install Zip HydroTap Install Rail with waterblock 15mm in 1/2" BSP out',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.08',
        'description' => 'Integrated Raised Font 135mm HydroTap Classic, Classic Plus & Wave, Matt Black',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.09',
        'description' => 'HydroTap G5 Classic Plus boiling ambient 160 Matt Black Work',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.10',
        'description' => 'HydroTap and HydroChill Installation',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 17,
        'item_code' => '17.11',
        'description' => 'Zip HydroTap G4 & G5 Limescale filter kit for work',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    // Leak Detection System
    [
        'template_section_id' => 17,
        'item_code' => '17.12',
        'description' => '1 Zone Leak Detection - Allow for a 1zone water leak detection system to include control panel with visual & audible alarm. A solenoid valve will be installed on the BCWS incoming which will shut off in the event of leak being detected.',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

      [
        'template_section_id' => 18,
        'item_code' => '18.01',
        'description' => 'No Works',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 19,
        'item_code' => '19.01',
        'description' => 'Builders Works - Allowance for Builders work to fulfil outlined works',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 0,
    ],

     [
        'template_section_id' => 20,
        'item_code' => '20.01',
        'description' => 'WF1 - Allowance to Paint proposed feature wall in XXXX paint, as per the Wall Finishes Drawing',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 6.50,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.02',
        'description' => 'New Partition Decoration - One mist coat and two full coats of emulsion paint to all new partitions',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 6.50,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.03',
        'description' => 'Existing Wall Decoration - Allow to decorate existing walls with two coats white vinyl matt',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 6.50,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.04',
        'description' => 'Bulkhead Decoration - Allowance to paint bulkheads above glass partitions',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 12.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.05',
        'description' => 'Decoration to existing wrapped columns',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 50.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.06',
        'description' => 'MF Ceiling Decoration - Allow to decorate MF ceilings',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 6.50,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.07',
        'description' => 'New Skirting Decoration - One undercoat and one eggshell to all new skirting',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 12.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.08',
        'description' => 'Existing Skirting Decoration - Decorate existing skirtings',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 12.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.09',
        'description' => 'Existing Door Frame Decoration - Allow decorate existing doors frame, door laminate finish',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 70.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.10',
        'description' => 'Window Frame and Sills - Allowance to paint exisiting window frames and sills',
        'quantity' => 1,
        'unit' => 'No',
        'rate' => 85.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 20,
        'item_code' => '20.11',
        'description' => 'Allowance to Spray Mechanical Services, Including all FCUS/Ductwork and Ventilation Equipment in White RAL 9010',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

      [
        'template_section_id' => 21,
        'item_code' => '21.01',
        'description' => 'Sound Masking System - To supply, install, tune and commission the LogiSon sound masking system to all Open Plan/Breakout/Cellular Office/Meeting Room/Cafe/Circulation zones, during/ outside of normal working hours. The system is broken down into zones of 3no loudspeakers. Each zone has its own sound generator (hub) and provides both independent third octave frequency and volume control. Each independent zone is digitally tuned, on site, to ensure both performance and comfort.',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 21,
        'item_code' => '21.02',
        'description' => 'Supply & Install Kvadrat Steelcut Trio Colour TBC - 25mm Wall Track System to Meeting Room/Office',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 22,
        'item_code' => '22.01',
        'description' => 'Supply and install XXXX carpet tile - Colour:TBC, Complete with all necessary adhesives.',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 24.89,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.02',
        'description' => 'Supply and Install XXXX LVT  col: TBC, Complete with all necessary adhesives.',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 49.11,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.03',
        'description' => 'Supply and Install XXXX Looselay Vinyl flooring directly to RAF  col: TBC, Complete with all necessary adhesives.',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 49.11,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.04',
        'description' => 'Supply and Install XXXX Anti Static Vinyl Tiles to Comms Room, Complete with all necessary adhesives.',
        'quantity' => 1,
        'unit' => 'M2',
        'rate' => 65.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.05',
        'description' => 'Subfloor Preparations',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.06',
        'description' => 'Supply & Installation of 6mm Ply floor preparation',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.07',
        'description' => 'Supply & Installation of 12mm Ply floor preparation',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.08',
        'description' => 'Supply & Installation Ditra Matting to underside of proposed porcelain tile locations',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.09',
        'description' => 'Preparations & Trims',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.10',
        'description' => 'Supply and install Aluminium Transition Trims',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.11',
        'description' => 'Supply and install Brass Effect Transition Trims',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.12',
        'description' => 'Supply and install Nosings In Black Anodised with matching black insert.',
        'quantity' => 1,
        'unit' => 'Lm',
        'rate' => 22.00,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 22,
        'item_code' => '22.13',
        'description' => 'Material Distribution to required areas',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 375.04,
        'mark_up' => 30,
    ],

     [
        'template_section_id' => 24,
        'item_code' => '24.01',
        'description' => 'Teapoint - Supply & Installation of Tea point similar to Howdens Clerkenwell Range with Matt finish doors and standard Carcass. Laminate worktop, inclusive of all white goods, Integrated larger Fridge, Dishwasher included',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 24,
        'item_code' => '24.02',
        'description' => 'Drinks Station - Supply & Installation of Drinks Station similar to Howdens Clerkenwell Range with Matt finish doors and standard Carcass. Laminate worktop, inclusive of all white goods, Integrated larger Fridge, Dishwasher included',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 24,
        'item_code' => '24.03',
        'description' => 'Splashback - Allowance to supply and install XXXX tile splashback to teapoint',
        'quantity' => 3,
        'unit' => 'Lm',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 25,
        'item_code' => '25.01',
        'description' => 'Allowance to Supply & Install perimeter Chain Operated Solarview 2% Blinds 900mm',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 25,
        'item_code' => '25.02',
        'description' => 'First Floor - Kurolok RL - Electric Radio Operated Window Blind - 1700x3000mm with Solarview Sunscreen',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 25,
        'item_code' => '25.03',
        'description' => 'First Floor - Kurolok RL - Electric Radio Operated Window Blind - 2400x3000mm with Solarview Sunscreen',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 25,
        'item_code' => '25.04',
        'description' => 'First Floor - Kurolok RL - Electric Radio Operated Window Blind - 2600x3000mm with Solarview Sunscreen',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 25,
        'item_code' => '25.05',
        'description' => 'Allowance to Supply & Install partition Voile Curtains to proposed locations',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 26,
        'item_code' => '26.01',
        'description' => 'Allowance to corporate signage (Design TBC)',
        'quantity' => 1,
        'unit' => 'PC',
        'rate' => 1500.00,
        'mark_up' => 30,
    ],

    [
        'template_section_id' => 27,
        'item_code' => '27.01',
        'description' => 'Allowance to Design, Fabricate and Install a bespoke staircase to the proposed location',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    [
        'template_section_id' => 27,
        'item_code' => '27.02',
        'description' => 'Allowance to supply & install balustrade to perimeter opening',
        'quantity' => 1,
        'unit' => 'Item',
        'rate' => 0,
        'mark_up' => 30,
    ],
    
        ];

        TemplateItem::insert($data);

    }
}
